version: '3.8'

services:

  club:
    image: omarazzouz/club:latest
    container_name: club-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - pidev-network

  evenement:
    image: omarazzouz/evenement:latest
    container_name: evenement-service
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - pidev-network

networks:
  pidev-network:
    driver: bridge
